### ISSUE TITLE
xiaomi 12/moto edge x30(or any device with sm8450) sms＆ims error

### ISSUE THREAD

**Issue by terminuss** [phhusson/treble_experimentations#2246]
Now gsi is able to boot on devices with sm8450.But sms doesn't work.And ims settings shows "not supported" .I tried to install q-ims.apk or ims.apk from the stock rom.Still ,ims does work at all.

All bootable gsi has the same problem.

**Comment by phhusson** [comment]
Yup that's a known issue.
It should be fixed when I get such a device, though I have no short term plan on buying one.

**Comment by phhusson** [comment]
Just to detail my last sentence: I don't receive anywhere close to enough money as donations to buy a 8gen1 device, so if I buy a 8gen1 device it's on because I decide I want one, and considering I bought a Galaxy S22, that's very unlikely.

**Comment by hk56184172** [comment]
so how could i fix it?

**Comment by phhusson** [comment]
@AndyCGYan fixed it, you can now just install https://treble.phh.me/stable/ims-caf-s.apk and it should fix ims on 8 gen 1.

**Comment by AndyCGYan** [comment]
> @AndyCGYan fixed it, you can now just install https://treble.phh.me/stable/ims-caf-s.apk and it should fix ims on 8 gen 1.

Received feedback from CoolAPK that it still isn't working on Moto/Lenovo QCOM AIDL, probably needs separate treatment like Moto QCOM HIDL. I'll work on that when I get a chance to.

**Comment by Jheff24** [comment]
Any fix for sms moto x30 snap8gen1? :(
