### ISSUE TITLE
[AOSP 10 v204] Huawei P8 Lite 2017

### ISSUE THREAD

**Issue by redmusicxd** [phhusson/treble_experimentations#763]
~~media is not working like no video no audio, a blind and deaf phone(seems like it can't load android.hardware.media)~~
~~webpages are not loading and after some time the app crashes (or at least that's what chrome does)~~
~~GPS does not work, the GPS Test App crashes and OsmAnd can't get a location.~~
~~Camera app doesn't even open but i guess it's because of the media thing.~~
~~I attached a logcat and also a dmesg~~

~~[dmesg.txt](https://github.com/phhusson/treble_experimentations/files/3707367/dmesg.txt)~~

~~[quack.txt](https://github.com/phhusson/treble_experimentations/files/3707387/quack.txt)~~

**Comment by 0x15f2d** [comment]
seems like thats your vendor or boot problem. not the gsi itself.

**Comment by phhusson** [comment]
first rule of my GSI is that it's never vendor's fault if it's OEM vendor. which is the case presently.
And then, that's not even right, that's probably bugs of mine.

@redmusicxd that's three issues, not one, that's annoying. anyway

1. media, try to do `setprop ctl.start media.swcodec` as root, and see if media works after that (that's not persistent, so don't reboot)
2. "webpages are not loading" you mean webview is broken? sounds like a bug in the gapps you flashed
3. "after some time chrome crashes" yeah that's a known bug fixed in next version
4. I don't see gps test app crash in your logs, and all seem to say GPS works fine in yours logs... just put your device outside and wait longer?
5. camera nope that's not because of media thing, it's because the camera fix patch you have is broken (since your device doesn't have an actual oem treblized camera)

**Comment by 0x15f2d** [comment]
my phone can't flash it due to lack of memory but i can assure that android 9 works well with my device. except secure boot password confirmation before booting the actual system (if you typed wrong password it will say the phone's userdata broken and needs a factory reset. but rebooting it and typing the correct password will boot the os normally).

this will not happen on android 8 gsi though.

the vendor and boot that compatible with all of your gsi images is just android 8's boot and vendor.

**Comment by 0x15f2d** [comment]
@phhusson Not related. But my Pixel 1 phone has the audio ic broken. Will this command `setprop ctl.start media.swcodec` work? Desperately wanna make it work without fixing the motherboard. (my screen broken so I can't interact with it. plus cant unlock by adb)

Or like have some sort of workaround for software audio processing.

**Comment by redmusicxd** [comment]
**UPDATE:**
The new v201 version solves most of the problems i stated before except that camera is still crashing.
here's a logcat 
[quack_camera.txt](https://github.com/phhusson/treble_experimentations/files/3775442/quack_camera.txt)

**Comment by 0x15f2d** [comment]
have you tried turning off the dnd? dnd causes lots of camera problems on my phone.

**Comment by redmusicxd** [comment]
Camera still not working with v204 update(clean install).
Here is ```adb shell dumpsys media.camera```
[hi6250.txt](https://github.com/phhusson/treble_experimentations/files/3849151/hi6250.txt)
And ```adb shell logcat```
[hi6250_log.txt](https://github.com/phhusson/treble_experimentations/files/3849156/hi6250_log.txt)

**Comment by redmusicxd** [comment]
Fix: [Download](https://sourceforge.net/projects/darkjoker360-developements/files/Huawei/P8%20Lite%202017/Android-10/Android-10_patch.zip/download)
Credit: @DarkJoker360
